# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Users
u1 = User.create!(email: "nkiruka@example.com", password: "password1", first_name: "Nkiruka", last_name: "Odu", location: "Toronto")
u2 = User.create!(email: "bob@example.com", password: "password2", first_name: "Bob", last_name: "Smith", location: "Vancouver")
u3 = User.create!(email: "manav@example.com", password: "password3", first_name: "Manav", last_name: "P", location: "Montreal")
u4 = User.create!(email: "dave@example.com", password: "password4", first_name: "Dave", last_name: "Brown", location: "Calgary")
u5 = User.create!(email: "eve@example.com", password: "password5", first_name: "Eve", last_name: "Davis", location: "Ottawa")
u6 = User.create!(email: "frank@example.com", password: "password6", first_name: "Frank", last_name: "Miller", location: "Edmonton")
u7 = User.create!(email: "grace@example.com", password: "password7", first_name: "Grace", last_name: "Wilson", location: "Winnipeg")
u8 = User.create!(email: "henry@example.com", password: "password8", first_name: "Henry", last_name: "Clark", location: "Halifax")
u9 = User.create!(email: "ivy@example.com", password: "password9", first_name: "Ivy", last_name: "Martin", location: "Quebec City")
u10 = User.create!(email: "jack@example.com", password: "password10", first_name: "Jack", last_name: "Wright", location: "Regina")
u11 = User.create!(email: "admin@buybuy.com", password:"admin123", first_name: "Admin", last_name: "Admin", location: "Global", admin: true)
u12 = User.create!(email: "lisa@example.com", password: "password12", first_name: "Lisa", last_name: "Reynolds", location: "Saskatoon")
u13 = User.create!(email: "mark@example.com", password: "password13", first_name: "Mark", last_name: "Anderson", location: "Red Deer")
u14 = User.create!(email: "nina@example.com", password: "password14", first_name: "Nina", last_name: "Lopez", location: "Kelowna")
u15 = User.create!(email: "omar@example.com", password: "password15", first_name: "Omar", last_name: "Benson", location: "Thunder Bay")
u16 = User.create!(email: "paula@example.com", password: "password16", first_name: "Paula", last_name: "Nguyen", location: "St. John's")

# Categories
c1 = Category.create!(name: "Electronics")
c2 = Category.create!(name: "Automobiles")
c3 = Category.create!(name: "Clothing")
c4 = Category.create!(name: "Home & Garden")
c5 = Category.create!(name: "Toys")
c6 = Category.create!(name: "Fashion & Beauty")

# Products
Product.create!(name: "Wireless Mouse", description: "Ergonomic wireless mouse with adjustable DPI and long battery life, perfect for both office and gaming use.", image: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg", price_in_cents: 2500, quantity: 10, swappable: false, category_id: c1.id, user_id: u1.id)
Product.create!(name: "2015 Toyota Camry", description: "A reliable mid-size sedan with excellent fuel economy, spacious interior, and well-maintained history.", image: "https://images.pexels.com/photos/11285174/pexels-photo-11285174.jpeg", price_in_cents: 1800000, quantity: 1, swappable: false, category_id: c2.id, user_id: u1.id)
Product.create!(name: "Men's Jacket", description: "Warm and stylish jacket made from durable materials, ideal for cold weather and casual outings.", image: "https://images.pexels.com/photos/7823919/pexels-photo-7823919.jpeg", price_in_cents: 7500, quantity: 1, swappable: true, category_id: c3.id, user_id: u3.id)
Product.create!(name: "Garden Tool Set", description: "Complete set for gardening including trowel, pruners, gloves, and cultivator, designed for both beginners and pros.", image: "https://images.pexels.com/photos/6231726/pexels-photo-6231726.jpeg", price_in_cents: 3200, quantity: 8, swappable: false, category_id: c4.id, user_id: u4.id)
Product.create!(name: "Building Blocks Set", description: "Creative toy blocks for kids to build and develop fine motor skills and imaginative play.", image: "https://images.pexels.com/photos/3661351/pexels-photo-3661351.jpeg", price_in_cents: 1800, quantity: 15, swappable: true, category_id: c5.id, user_id: u5.id)
Product.create!(name: "Bluetooth Speaker", description: "Marshall portable high-quality sound speaker with Bluetooth connectivity and deep bass.", image: "https://images.pexels.com/photos/1706694/pexels-photo-1706694.jpeg", price_in_cents: 6000, quantity: 4, swappable: true, category_id: c1.id, user_id: u6.id)
Product.create!(name: "Used Honda Civic", description: "Reliable city car with low mileage, fuel-efficient, and well-maintained for everyday commuting.", image: "https://images.pexels.com/photos/15296580/pexels-photo-15296580.jpeg", price_in_cents: 1550000, quantity: 1, swappable: false, category_id: c2.id, user_id: u7.id)
Product.create!(name: "Women's Winter Coat", description: "Stylish and warm winter coat made with insulated fabric for extreme cold weather comfort.", image: "https://images.pexels.com/photos/7494681/pexels-photo-7494681.jpeg", price_in_cents: 8500, quantity: 2, swappable: true, category_id: c3.id, user_id: u8.id)
Product.create!(name: "LED Desk Lamp", description: "Energy-efficient lamp for your home office with adjustable brightness and flexible arm.", image: "https://images.pexels.com/photos/112811/pexels-photo-112811.jpeg", price_in_cents: 3000, quantity: 6, swappable: true, category_id: c4.id, user_id: u9.id)
Product.create!(name: "RC Car", description: "Fast and fun remote-controlled car with rechargeable battery and responsive controls.", image: "https://images.pexels.com/photos/13047780/pexels-photo-13047780.jpeg", price_in_cents: 4200, quantity: 3, swappable: true, category_id: c5.id, user_id: u10.id)
Product.create!(name: "Mountain Bike", description: "18-speed aluminum frame mountain bike with front suspension, ideal for rugged terrain.", image: "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg", price_in_cents: 85000, quantity: 2, swappable: true, category_id: c2.id, user_id: u1.id)
Product.create!(name: "Used Toyota Corolla", description: "Fuel-efficient 2012 sedan with clean interior and low mileage, perfect for city driving.", image: "https://images.pexels.com/photos/29458514/pexels-photo-29458514.jpeg", price_in_cents: 1200000, quantity: 1, swappable: false, category_id: c2.id, user_id: u2.id)
Product.create!(name: "Motorcycle Helmet", description: "DOT certified full-face helmet offering superior protection and comfort for riders.", image: "https://images.pexels.com/photos/1396642/pexels-photo-1396642.jpeg", price_in_cents: 15000, quantity: 3, swappable: true, category_id: c2.id, user_id: u3.id)
Product.create!(name: "Car Jack", description: "Hydraulic car jack with 2-ton lifting capacity, compact and easy to use.", image: "https://images.pexels.com/photos/4116206/pexels-photo-4116206.jpeg", price_in_cents: 6000, quantity: 1, swappable: false, category_id: c2.id, user_id: u4.id)
Product.create!(name: "Roof Rack", description: "Universal aluminum roof rack, strong and lightweight for extra cargo space.", image: "https://images.pexels.com/photos/4828996/pexels-photo-4828996.jpeg", price_in_cents: 18000, quantity: 1, swappable: true, category_id: c2.id, user_id: u5.id)
Product.create!(name: "Lipstick Set", description: "Matte long-lasting lipsticks in multiple shades, perfect for all occasions.", image: "https://images.pexels.com/photos/2586073/pexels-photo-2586073.jpeg", price_in_cents: 3200, quantity: 10, swappable: true, category_id: c6.id, user_id: u6.id)
Product.create!(name: "Leather Handbag", description: "Genuine leather crossbody bag with multiple compartments and stylish design.", image: "https://images.pexels.com/photos/3661622/pexels-photo-3661622.jpeg", price_in_cents: 7200, quantity: 2, swappable: false, category_id: c6.id, user_id: u7.id)
Product.create!(name: "Gold Hoop Earrings", description: "18k plated, medium size gold hoop earrings, elegant and lightweight.", image: "https://images.pexels.com/photos/18075559/pexels-photo-18075559.jpeg", price_in_cents: 4500, quantity: 5, swappable: true, category_id: c6.id, user_id: u8.id)
Product.create!(name: "Men’s Loafers", description: "Suede loafers, size 10, comfortable for both casual and formal wear.", image: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg", price_in_cents: 5500, quantity: 2, swappable: false, category_id: c6.id, user_id: u9.id)
Product.create!(name: "Perfume Set", description: "Designer perfume gift pack with multiple fragrances, perfect for gifting.", image: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg", price_in_cents: 6500, quantity: 1, swappable: true, category_id: c6.id, user_id: u10.id)
Product.create!(name: "Stuffed Bear", description: "Soft plush teddy bear, perfect as a comforting gift for kids and adults.", image: "https://images.pexels.com/photos/5786759/pexels-photo-5786759.jpeg", price_in_cents: 1800, quantity: 7, swappable: true, category_id: c5.id, user_id: u1.id)
Product.create!(name: "Lego Creator Set", description: "Multi-model building toy that encourages creativity and problem-solving skills.", image: "https://www.lego.com/cdn/cs/set/assets/blt7b0edf9d05090dfd/10696_alt2.jpg?format=webply&fit=bounds&quality=75&width=1200&height=1200&dpr=1", price_in_cents: 4600, quantity: 3, swappable: false, category_id: c5.id, user_id: u2.id)
Product.create!(name: "Remote-Control Drone", description: "Mini drone for kids with easy controls and durable build for outdoor fun.", image: "https://images.pexels.com/photos/15189501/pexels-photo-15189501.jpeg", price_in_cents: 8900, quantity: 2, swappable: true, category_id: c5.id, user_id: u3.id)
Product.create!(name: "Puzzle Board", description: "Wooden alphabet puzzle for early childhood learning and hand-eye coordination.", image: "https://images.pexels.com/photos/1153929/pexels-photo-1153929.jpeg", price_in_cents: 1400, quantity: 10, swappable: true, category_id: c5.id, user_id: u4.id)
Product.create!(name: "RC Truck", description: "Rechargeable off-road truck with durable tires, suitable for rough terrains.", image: "https://images.pexels.com/photos/20591146/pexels-photo-20591146.jpeg", price_in_cents: 6200, quantity: 1, swappable: false, category_id: c5.id, user_id: u5.id)
Product.create!(name: "Men's Polo Shirt", description: "Slim fit, breathable cotton polo shirt, ideal for casual and semi-formal occasions.", image: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg", price_in_cents: 3200, quantity: 6, swappable: true, category_id: c3.id, user_id: u16.id)
Product.create!(name: "Kids Pajamas Set", description: "Soft cotton nightwear set for kids, comfortable for all seasons.", image: "https://images.pexels.com/photos/29856955/pexels-photo-29856955.jpeg", price_in_cents: 2700, quantity: 4, swappable: false, category_id: c3.id, user_id: u1.id)
Product.create!(name: "Women’s Jeans", description: "Stretch fit, blue denim jeans designed for comfort and style.", image: "https://images.pexels.com/photos/1082528/pexels-photo-1082528.jpeg", price_in_cents: 4800, quantity: 3, swappable: true, category_id: c3.id, user_id: u2.id)
Product.create!(name: "Winter Sweater", description: "Wool sweater size M, warm and cozy for cold weather.", image: "https://images.pexels.com/photos/2658451/pexels-photo-2658451.jpeg", price_in_cents: 5800, quantity: 2, swappable: true, category_id: c3.id, user_id: u3.id)
Product.create!(name: "Men’s Tracksuit", description: "Hoodie and joggers combo, perfect for workouts or casual wear.", image: "https://images.pexels.com/photos/5066568/pexels-photo-5066568.jpeg", price_in_cents: 6500, quantity: 2, swappable: false, category_id: c3.id, user_id: u4.id)
Product.create!(name: "Tablet", description: "10-inch Android tablet with high-resolution display and long battery life.", image: "https://images.pexels.com/photos/221185/pexels-photo-221185.jpeg", price_in_cents: 38000, quantity: 1, swappable: false, category_id: c1.id, user_id: u6.id)
Product.create!(name: "Wireless Earbuds", description: "Bluetooth noise-canceling wireless earbuds with secure fit and quality sound.", image: "https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg", price_in_cents: 7000, quantity: 3, swappable: true, category_id: c1.id, user_id: u7.id)
Product.create!(name: "Power Bank", description: "10,000 mAh USB-C output power bank for fast charging on the go.", image: "https://images.pexels.com/photos/8137313/pexels-photo-8137313.jpeg", price_in_cents: 2500, quantity: 4, swappable: false, category_id: c1.id, user_id: u8.id)
Product.create!(name: "LED Monitor", description: "24” Full HD screen LED monitor with vibrant colors and slim design.", image: "https://images.pexels.com/photos/1714204/pexels-photo-1714204.jpeg", price_in_cents: 15000, quantity: 1, swappable: true, category_id: c1.id, user_id: u9.id)
Product.create!(name: "Digital Camera", description: "Compact 16MP digital camera with zoom and image stabilization.", image: "https://images.pexels.com/photos/212372/pexels-photo-212372.jpeg", price_in_cents: 12500, quantity: 1, swappable: true, category_id: c1.id, user_id: u10.id)
Product.create!(name: "Lawn Mower", description: "Electric push mower with adjustable cutting height and easy maneuverability.", image: "https://images.pexels.com/photos/4162011/pexels-photo-4162011.jpeg", price_in_cents: 42000, quantity: 1, swappable: false, category_id: c4.id, user_id: u11.id)
Product.create!(name: "Indoor Plant Set", description: "Set of 3 succulents perfect for home or office decor, easy to maintain.", image: "https://images.pexels.com/photos/793012/pexels-photo-793012.jpeg", price_in_cents: 1900, quantity: 5, swappable: true, category_id: c4.id, user_id: u12.id)
Product.create!(name: "Hose Nozzle", description: "Adjustable spray pattern hose nozzle, durable and easy to use.", image: "https://images.pexels.com/photos/32532077/pexels-photo-32532077.jpeg", price_in_cents: 1100, quantity: 2, swappable: true, category_id: c4.id, user_id: u13.id)
Product.create!(name: "Flower Vase", description: "Ceramic, tall design flower vase perfect for fresh or artificial flowers.", image: "https://images.pexels.com/photos/2300713/pexels-photo-2300713.jpeg", price_in_cents: 2400, quantity: 3, swappable: false, category_id: c4.id, user_id: u14.id)
Product.create!(name: "Tree Trimmer", description: "Heavy-duty pruning tool designed for trimming branches and shaping trees.", image: "https://images.pexels.com/photos/24595770/pexels-photo-24595770.jpeg", price_in_cents: 4700, quantity: 1, swappable: true, category_id: c4.id, user_id: u15.id)


# Chats
Chat.create!(sender_id: u1.id, receiver_id: u2.id, content: "Hi Bob, I am interested in Camry")
Chat.create!(sender_id: u2.id, receiver_id: u1.id, content: "Hey Alice, yes it’s available!")
Chat.create!(sender_id: u3.id, receiver_id: u4.id, content: "Dave, is the garden tool set still for sale?")
Chat.create!(sender_id: u4.id, receiver_id: u3.id, content: "Yes Carol, you can pick it up this weekend.")
Chat.create!(sender_id: u5.id, receiver_id: u1.id, content: "Is the building blocks set still available?")
Chat.create!(sender_id: u6.id, receiver_id: u7.id, content: "Grace, your Civic listing looks nice.")
Chat.create!(sender_id: u7.id, receiver_id: u6.id, content: "Thanks Frank, it's still available.")
Chat.create!(sender_id: u8.id, receiver_id: u9.id, content: "Henry, interested in a coat trade?")
Chat.create!(sender_id: u9.id, receiver_id: u8.id, content: "Sure Ivy, let’s chat!")
Chat.create!(sender_id: u10.id, receiver_id: u5.id, content: "Eve, the RC car looks great!")
Chat.create!(sender_id: u12.id, receiver_id: u13.id, content: "Hey Mark, can you ship the bike to Saskatoon?")
Chat.create!(sender_id: u13.id, receiver_id: u12.id, content: "Yes Lisa, shipping available.")
Chat.create!(sender_id: u14.id, receiver_id: u15.id, content: "Omar, are the storybooks suitable for 5-year-olds?") 
Chat.create!(sender_id: u15.id, receiver_id: u14.id, content: "Yes Nina, perfect for early readers.")
Chat.create!(sender_id: u16.id, receiver_id: u12.id, content: "Lisa, interested in a swap for the fiction books?") 

